### PR TITLE
Do not try to instanciate abstract class Visibility

### PR DESCRIPTION
**Pull request by Morriar**
We'll have to check why Sorbet doesn't see this.

### CODE REVIEW

**Review by KaanOzkan — APPROVED** [review]
Probably because this definition in `printer` is not abstract? https://github.com/Shopify/rbi/blob/903a2f73e6813619481fa08b6c7b11045b8123f7/lib/rbi/printer.rb#L573

**Comment by vinistock** [comment]
Do we still need `Visibility#initialize`? Should it even exist? https://github.com/Shopify/rbi/blob/5033e1bac80d19126ff278a31680ad785cd1470f/lib/rbi/model.rb#L843

**Comment by Morriar** [comment]
> Probably because this definition in `printer` is not abstract?

I don't think so. It doesn't seem to be checked either on a [simpler case](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Foo%0A%20%20extend%20T%3A%3AHelpers%0A%0A%20%20abstract!%0Aend%0A%0AFoo.new).

**Comment by Morriar** [comment]
> Do we still need `Visibility#initialize`? Should it even exist?

Yes, we still need Visibility to set its internal state (@visivility) and call super. Sorbet should prevent calling `.new` tho since it's abstract.

**Pull request merged**
